name: Scheduled Workflow

on:
  schedule:
    - cron: '*/2 * * * *' # Runs every hour

jobs:
  Hello_World:
    runs-on: ubuntu-latest

    steps:
      - name: echo current datetime
        run: echo "The current server time is $(date)"
